# -*- coding: utf-8 -*-
"""Atividade

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pDPAf2W6Z273ubX87o-Y9bTlEiBdODFM
"""

def analiseAmbiental():
  print("--- Análise Ambiental de Locais Urbanos ---")
  dadosLocais = [
    ["Guaianases 22hr", 20, 88, 86],
    ["Guaianases 12hr", 27, 44, 85],
    ["Itaquera 22hr", 20, 88, 110],
    ["Itaquera 12hr", 27, 51, 66],
    ["Tatuape 22hr", 20, 82, 84],
    ["Tatuape 12hr", 29, 39, 107]
  ]

  for local in dadosLocais:
    nome, temp, umid, iqa = local

    print(f"\nLocal: {nome}")

    for indice, valor in enumerate([temp, umid, iqa]):
      if indice == 0:
        print(f" Temperatura: {valor}°C")
      elif indice == 1:
        print(f" Umidade: {valor}%")
      else:
        match valor:
          case v if v <= 50:
            qualidade = "Boa"
          case v if v <= 100:
            qualidade = "Moderada"
          case v if v <= 199:
            qualidade = "Inadequada"
          case v if v <= 299:
            qualidade = "Ruim"
          case v if v <= 399:
            qualidade = "Muito Ruim"
          case _:
            qualidade = "Perigosa"

        print(f" IQA: {valor} ({qualidade})")

    penalizacao_temp = abs(temp - 22) / 10
    penalizacao_umid = abs(umid - 50) / 20
    penalizacao_iqa = iqa / 200

    nota_conforto = max(0, 10 - (penalizacao_temp + penalizacao_umid + penalizacao_iqa))

    print(f" Nota de Conforto Urbano: {nota_conforto:.2f}/10")

analiseAmbiental()



### PARTE 2 Navegação e Evacuação Espacial


print("--- Navegação e Evacuação Espacial ---")

locais = ["Quarto", "Sala", "Corredor 1", "Escada 1", "Corredor 2", "Escada 2", "Porta Principal", "Saida"]
obstaculos = ["caminho livre", "porta trancada", "extintor", "escada estreita", "caminho livre", "escada estreita", "porta aberta", "saida"]
inventario = {"chave": False, "energia": 18, "itens": []}

posicao = 0
visitas_sala = 0
passos = 0

while True:
  if inventario["energia"] <= 0:
    print("O agente ficou sem energia. Evacuação falhou.")
    break

  local_atual = locais[posicao]
  obstaculo_atual = obstaculos[posicao]
  passos += 1

  print(f"\nAgente está em: {local_atual} | Obstáculo: {obstaculo_atual}")

  if obstaculo_atual == "saida":
    print("O agente conseguiu evacuar para a rua com sucesso!")
    break

  if obstaculo_atual == "caminho livre":
    posicao += 1

  elif obstaculo_atual == "porta trancada":
    visitas_sala += 1

    if inventario["chave"]:
      print("Agente usa a chave para abrir a porta da Sala.")
      inventario["itens"].append("porta aberta")
      posicao += 1
    else:
      if visitas_sala == 2:
        print("Agente encontrou a chave na Sala na segunda tentativa!")
        inventario["chave"] = True
        inventario["itens"].append("chave")
        print("Agente usa a chave recém-encontrada para abrir a porta.")
        posicao += 1
      else:
        print("Agente não tem chave. Tentando novamente na Sala...")

  elif obstaculo_atual == "extintor":
    print("Agente encontra um extintor no caminho do corredor.")

    if inventario["energia"] > 1:
      print("Agente Pega o Extintor")
      inventario["energia"] -= 1
      inventario["itens"].append("Extintor")
      posicao += 1
    else:

      print("Agente não tem energia suficiente para mover o extintor.")

      posicao -= 1

  elif obstaculo_atual == "escada estreita":
    if inventario["energia"] > 2:
      print("Agente desce a escada com cuidado.")
      inventario["energia"] -= 2
      posicao += 1
    else:
      print("Agente não tem energia suficiente para descer a escada.")
      posicao -= 1

  elif obstaculo_atual == "porta aberta":
    print("Agente passa pela porta sem problemas.")
    posicao += 1

  inventario["energia"] -= 1


print("\n--- RESULTADO FINAL ---")
print(f"Passos dados: {passos}")
print(f"Energia restante: {inventario['energia']}")
print(f"Itens no inventário: {inventario['itens']}")
print(f"Chave encontrada: {inventario['chave']}")

